export enum Status {
  PENDING_PAYMENT = 'PENDING PAYMENT',
  PAYMENT_SUCCESSFUL = 'PAYMENT SUCCESSFUL',
  PAYMENT_FAILED = 'PAYMENT FAILED',

  ORDER_IN_PROGRESS = 'MAKING YOUR ORDER',
  ORDER_SUCCESSFUL = 'ORDER SUCCESSFUL',
  ORDER_FAILED = 'ORDER FAILED',

  WAITING_MOTOBOY = 'WAITING MOTOBOY',
  DELIVERING = 'DELIVERING',

  SUCESSFULL = 'SUCESSFUL',
  CANCELLED = 'CANCELLED',
}
